databases:
  - name: Nahid1911
    databaseName: nahid1911
    user: nahid1911_user
    ipAllowList: []

services:
  - type: web
    name: rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nahid1911
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
